name: auro-release

on:
  pull_request:
    types: [closed]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    -
      if: github.event.pull_request.merged == true
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Create Release
      uses: softprops/action-gh-release@v1
