name: auto-release

on:
  pull_request:
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    -
      if: github.event.pull_request.merged == true
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
